### ISSUE TITLE
Video controls not scaling to item width

### ISSUE THREAD

**Issue by bitbay** [MurhafSousli/ngx-gallery#253]
#### What is the expected behavior?
Browser controls should fill the width of the gallery video item. 

#### What is the current behavior?
Not scaling to item width.

#### What are the steps to reproduce?
Now this is a tricky one... couldn't find a method to reproduce - need help!

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/2558741/50104578-56ce1200-0222-11e9-8b52-aa852d5f76ed.png)
Demo page failing as well.
https://murhafsousli.github.io/ngx-gallery/#/advanced

**Comment by bitbay** [comment]
Thanks @MurhafSousli 
To me it looks like it has to do with chrome not getting initial dimensions of the video before any data loaded, and can't define the correct aspect ratio (?)...
Sadly, this is a show-stopper bug for us now. Any known workarounds?

**Comment by MurhafSousli** [comment]
This bug was caused by Chrome and it is fixed now from their side

**Comment by bitbay** [comment]
> This bug was caused by Chrome and it is fixed now from their side

Could You share a link to the bug report/fix/status?

**Comment by MurhafSousli** [comment]
No, I don't have it but I can tell because it was fixed without an update from this package

**Comment by bitbay** [comment]
What version of Chrome You use?
I'm using `Chrome Version 71.0.3578.98 (Official Build) (64-bit)` with `"@ngx-gallery/core": "^4.0.1"` and *the bug is still present*...
Reopen issue?

**Comment by MurhafSousli** [comment]
Same version 71.0.3578.98, I tried it from 2 different PCs, the centralized play button is removed from the HTML5 video player

**Comment by bitbay** [comment]
> the centralized play button is removed from the HTML5 video player
The _play button_ wasn't the real issue, the whole overlayed element is scaled wrong!
If You look at the attached screenshot, the seeker/slider (and the rect of the overlay) scales a bit over 50% of the components width.

**Comment by MurhafSousli** [comment]
@bitbay I really have no idea how can this be solved on Chrome! in my browser I don't get it anymore, as you can see in the source code, we don't have any extra configuration, it is just a translate3d moving the video element to the proper position! if you have any suggestion or got a solution, let me know
