### ISSUE TITLE
Replace hammerjs with native touch events

### ISSUE THREAD

**Issue by vpetrusevici** [MurhafSousli/ngx-gallery#449]
#### What is the expected behavior?
Use native pointermove event instead of outdated hammerjs.
#### What is the current behavior?
We should install and use hammerjs to enable touch events.

#### What is the use-case or motivation for changing an existing behavior?

Possibility to avoid additional dependency.

#### Is there anything else we should know?

I can try to implement it if you agree.

**Comment by vpetrusevici** [comment]
It also can be just another tree-shacking library like this one https://github.com/nolimits4web/swiper

**Comment by MurhafSousli** [comment]
Yes, you can try, PRs are welcome!

**Comment by vpetrusevici** [comment]
Added a draft PR as PoW

**Comment by MurhafSousli** [comment]
> Added a draft PR as PoW

Thanks, I will have a look!

**Comment by vpetrusevici** [comment]
@MurhafSousli I finished all related work. Hope I didn't miss any features

**Comment by vpetrusevici** [comment]
Hi, @MurhafSousli 
Sorry to bother you, but could you please check my PR?

**Comment by MurhafSousli** [comment]
@vpetrusevici  an update on this issue... version 8 removed the usage of HammerJs for mobile sliding! it does not use the native touch events either! it is now using the native scrolling to slide the gallery!

However, HammerJs is still used BUT only for sliding on desktop browser using the mouse.

Feedback is appreciated https://github.com/MurhafSousli/ngx-gallery/releases/tag/v8.0.0-beta.1

**Comment by vpetrusevici** [comment]
Thank you! I'll test it :)

**Comment by vpetrusevici** [comment]
Hi! I notice some update promlem in gallery thumbs https://1drv.ms/u/s!ArDpOrDSusKbvyki94glg5pxuZNB?e=h3S3aK

**Comment by MurhafSousli** [comment]
I didn't get it? could you please reproduce it [here ](https://stackblitz.com/edit/ngx-gallery-3e3kzf)

**Comment by MurhafSousli** [comment]
Should be fixed in v8.0.0-beta3

**Comment by vpetrusevici** [comment]
It's working well in a lightbox, but in a simple galley problem still exists. I think the problem in the async pipe. You can try to use this variant https://github.com/MurhafSousli/ngx-gallery/pull/483/files#diff-b9348fa0028b29ce8458b889a0dbfa72d9b766f99e4666c57e9392a5de5c7012 It should subscribe outside of ngZone and execute changes in ngZone

**Comment by MurhafSousli** [comment]
The problem is with the gallery size, if the gallery's width value has fraction e.g. 500.63px, then it will have this issue, but with the latest fix, I forced the gallery to have a fixed size value

**Comment by vpetrusevici** [comment]
I tried with beta4. The same behaviour

**Comment by vpetrusevici** [comment]
Tested on mobile. Here looks good

**Comment by MurhafSousli** [comment]
Can you test it with beta5?

**Comment by vpetrusevici** [comment]
I tested in chrome and android. Looks good. Only 1 bug found for SSR https://github.com/MurhafSousli/ngx-gallery/issues/532
